### ISSUE TITLE
User Story 2 - Anonymous Feedback

### ISSUE THREAD

**Issue by CamCove-Crichton** [CamCove-Crichton/love-running#2]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response**

## Acceptance Criteria

- Acceptance Criteria 1: The option should be provided as a checkbox
- Acceptance Criteria 2: The checkbox should be "checked" by default
- Acceptance Criteria 3: The option should appear next to the submit button
- Acceptance Criteria 4: After submitting the default submission confirmation should be adjusted to include the user name

## Tasks

- [x] Update the view: the poll design (HTML & CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
