### ISSUE TITLE
User Story: Signup with Social Media

### ISSUE THREAD

**Issue by CamCove-Crichton** [CamCove-Crichton/love-running#6]
In order to **sign up easier** as an **user**, I can **use my social media accounts to sign up with**

## Acceptance Criteria:

- Acceptance Criteria 1:  Option should be clearly visible
- Acceptance Criteria 2: It should be a clickable button
- Acceptance Criteria 3: It must should be just above the submit button
  
## Tasks:

- [ ] Task 1: Update the signup section (HTML & CSS) to include the relative social media signup options
- [ ] Task 2: Update the functionality (Javascript) to have event listeners on each of the social media signup options
- [ ] Task 3: Update unit test scripts
- [ ] Task 4: Test functionality
